# Generated by Django 5.1.4 on 2025-04-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideWise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='destination_location',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='trips',
            name='pickup_location',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
