# Generated by Django 5.0.6 on 2024-06-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RideWise', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='service',
            new_name='service_name',
        ),
    ]
