# Generated by Django 5.0.6 on 2024-07-13 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideWise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteroute',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_id',
        ),
        migrations.AddField(
            model_name='favoriteroute',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RideWise.user'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RideWise.user'),
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=100)),
                ('destination_location', models.CharField(max_length=100)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_minutes', models.FloatField()),
                ('surge_multiplier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('service_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RideWise.user')),
            ],
        ),
    ]
