# Generated by Django 5.0.6 on 2024-07-14 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideWise', '0002_remove_favoriteroute_user_id_remove_review_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteroute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RideWise.user'),
        ),
    ]
