# Generated by Django 5.0.6 on 2024-06-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RideWise', '0003_alter_trips_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ride',
        ),
    ]
