# Generated by Django 5.0.6 on 2024-06-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideWise', '0004_delete_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trips',
            name='time_minutes',
            field=models.FloatField(),
        ),
    ]
