# Generated by Django 5.0.6 on 2024-07-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RideWise', '0004_alter_review_user_alter_trips_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoriteroute',
            old_name='user',
            new_name='user_id',
        ),
    ]
