# Generated by Django 5.0.6 on 2024-07-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideWise', '0005_alter_review_rating_alter_trips_time_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='rating',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
    ]
