# Generated by Django 5.0.6 on 2024-07-09 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RideWise', '0006_trips_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='rating',
        ),
    ]
