# Generated by Django 5.0.6 on 2024-07-09 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RideWise', '0007_remove_trips_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='service_id',
            new_name='vehicle_type',
        ),
    ]
